### PR TITLE
Make it compatible with forms API (RC4)

### PR DESCRIPTION
**Pull request by yabab-dev**

### CODE REVIEW

**Comment by kamikaze** [comment]
make it compatible with tslint too? :)

**Comment by TareqElMasriDev** [comment]
Please merge it.

**Comment by valorkin** [comment]
I would love to, but I need CI build fix

**Comment by yabab-dev** [comment]
Sorry, I don't use TypeScript but I've commited some tslint fixes

**Comment by 0cv** [comment]
That seems to work well. But 2 remarks:
1. When doing `this.form.value`, an array is set of both the `id` and the `text`. I think it should be an array of just `id` instead.
2.  One slightly inconsistent point is when multiple is set to false, the value is set within an Array of 1 object. Logically, this should not be an array but a simple entry with the "id" as value. 

Either way, this pull request makes this plugin useful, looking forward to seeing that merged :)

**Comment by kruczjak** [comment]
Hi :) Anything new on this PR? :) It would be great seeing it merged :D

**Comment by valorkin** [comment]
@otelnov please check this one

**Comment by jvanharn** [comment]
Any progress on this PR?

**Comment by kruczjak** [comment]
I've tested version from @chymz fork on RC4 and it looks like it's working good with new forms using FormBuilder :)

**Comment by m-lessard** [comment]
So does that means that you are about to merge it?  Maybe you could provide kind of a roadmap of when you will merge it.  Couple of weeks?  Couple of months?  Looks like many people are waiting for this new version of your module.  Good for you that so many peoples are using it. Thanks!

**Comment by yabab-dev** [comment]
Update for rc6 comitted

**Comment by valorkin** [comment]
Awesome, I will merge and publish it asap

**Comment by fxcosta** [comment]
Sorry for the inconvenience. Any news about this PR?

**Comment by valorkin** [comment]
Thank you!
 Merged as a part of another PR

**Pull request closed without merging**
