### PR TITLE
#226 Update initData

### LINKED ISSUE #226: [initData] doesn't update
Hello,
changes on [initDate] don't cause the change in a component.

BR,
Marcin

### PR DESCRIPTION
**Pull request by marcin992**
resolves #226

### CODE REVIEW

**Comment by marcin992** [comment]
Hi, there are strange errors on travis, something with execSync package. Could you look at them?

**Comment by Namek** [comment]
@marcin992 don't you think that this would be a better approach? #223

**Comment by marcin992** [comment]
@Namek Yes, you're right. Thanks for comment. @valorkin please ignore this pullrequest

**Comment by valorkin** [comment]
ok, closed in favour of #223

**Comment by valorkin** [comment]
Thanks for your time anyway! :)

**Pull request closed without merging**
