### PR TITLE
fix issue #437

### PR DESCRIPTION
**Pull request by vixriihi**
This pr fixes issue #437 and makes the highlighter to hightlight the whole text instead of just first character

### CODE REVIEW

**Comment by BenDevelopment** [comment]
Can someone with write access merge this pull request ?

**Comment by valorkin** [comment]
Looks good to me! Thanks for helping

**Comment by caretro** [comment]
Can I ask you when this fix will be realesed in master branch? Thank you!

**Comment by valorkin** [comment]
I need to process ng2-table PRs today and will get back ng2-select
in nearest future 
ng2-bootstrap typeahead and ng2-select will be merged
because they are almost identical

**Comment by RoopeHakulinen** [comment]
@valorkin We'd be extremely grateful if you could just release a patch version 1.1.1 for this since it is quite essential for our product.

**Pull request merged**
