### PR TITLE
Fix for multiple selects on one page

### PR DESCRIPTION
**Pull request by qweritos**

### CODE REVIEW

**Comment by mpetkov** [comment]
Can this change be merged?  Every interface I work on has multiple select fields and I would like to use this plugin but currently can't because of this bug.

**Comment by thuynh** [comment]
This doesn't seem like it's working. Also, I think there's a typo:

`
if (srcElement.contains(context.element.nativeElement)
`

Suppose to be:

`
if (e.srcElement.contains(context.element.nativeElement)
`

However, I think the logic should be:

```
private getOffSideClickHandler(context:any) {
    return function (e:any) {
      if (e.target && e.target.nodeName === 'INPUT'
        && e.target.className && e.target.className.indexOf('ui-select') >= 0) {
        return;
      }

      if (context.element.nativeElement.contains(e.srcElement)
        && e.srcElement && e.srcElement.className &&
        e.srcElement.className.indexOf('ui-select') >= 0) {
        if (e.target.nodeName !== 'INPUT') {
          context.matchClick(null);
        }
        return;
      }

      context.inputMode = false;
      context.optionsOpened = false;
    };
  }
```

**Comment by Shootervm** [comment]
If someone needs quick fix before it will be merged/fixed, this is solution that should work (derivated from @thuynh , thanks)

```typescript
import {Component, OnInit, ElementRef} from 'angular2/core';
import {Select} from 'ng2-select';
import {FORM_DIRECTIVES, CORE_DIRECTIVES, NgClass} from 'angular2/common';

class OurSelect extends Select {
    constructor(public element:ElementRef) {
        super(element);
    }

    private getOffSideClickHandler(context:any) {
        return function (e:any) {
            if (e.target && e.target.nodeName === 'INPUT'
              && e.target.className && e.target.className.indexOf('ui-select') >= 0) {
                return;
            }

            if (context.element.nativeElement.contains(e.srcElement)
              && e.srcElement && e.srcElement.className &&
              e.srcElement.className.indexOf('ui-select') >= 0) {
                if (e.target.nodeName !== 'INPUT') {
                    context.matchClick(null);
                }
                return;
            }

            context.inputMode = false;
            context.optionsOpened = false;
        };
    }
}

@Component({
    selector: 'search-dropdown',
    template: `<div>
                    <ng-select [allow-clear]="true"
                               [items]="items"
                               (data)="refreshValue($event)"
                               [placeholder]="'Please select the tariff'">
                    </ng-select>
               </div>
               `,
    directives: [OurSelect, FORM_DIRECTIVES, CORE_DIRECTIVES, NgClass]
})
export class MassFixTariffDropdownComponent {
    /*(...code...)*/
}
```

**Comment by lpotapczuk** [comment]
@valorkin, can we have updated version on the npm? It seems to me, like that version on NPM is outdated, and the issue is still present there.

**Comment by Avien** [comment]
This is still happening.
When opening a dropdown, it doesn't close an already opened dropdown 
image

I am using version 1.2.0

**Comment by blubberbo** [comment]
+1

**Comment by arsyed04** [comment]
Any plans to resolve this issue?

**Pull request merged**
