### PR TITLE
fixed the disabled state

### PR DESCRIPTION
**Pull request by linusbrolin**
The disabled state wasn't working, due to the boolean used in the template only being a setter, not a getter.
Replaced with the private _disabled boolean instead.

### CODE REVIEW

**Comment by valorkin** [comment]
@linusbrolin can not agree,
can you just add getter for disabled?
because switching to _disabled removes call to .hideOptions

**Comment by linusbrolin** [comment]
Sure.
I just thought that the public disabled should only be a setter.
But if having a public getter is no problem, then I'll do that instead, no problem. :)

**Comment by linusbrolin** [comment]
status on this?

**Comment by valorkin** [comment]
Thanks, sorry for delay

**Pull request merged**
