### PR TITLE
avoid peer messages

### LINKED ISSUE #467: angular 2.0.1 cant install dependences.
Im trying to install ng2-select in angular 2.0.1, but it fails...

Anyone knows what change between versions?

UNMET PEER DEPENDENCY @angular/common@2.0.1
├── UNMET PEER DEPENDENCY @angular/compiler@2.0.1
├── UNMET PEER DEPENDENCY @angular/core@2.0.1
├── UNMET PEER DEPENDENCY @angular/forms@2.0.1
└── ng2-select@1.1.0 

npm WARN ng2-select@1.1.0 requires a peer of @angular/common@2.0.0 but none was installed.
npm WARN ng2-select@1.1.0 requires a peer of @angular/compiler@2.0.0 but none was installed.
npm WARN ng2-select@1.1.0 requires a peer of @angular/core@2.0.0 but none was installed.
npm WARN ng2-select@1.1.0 requires a peer of @angular/forms@2.0.0 but none was installed.

### PR DESCRIPTION
**Pull request by grauschnabel**
fixes #467

### CODE REVIEW

**Comment by AilisObrian** [comment]
ping?

**Comment by valorkin** [comment]
Will be merged and published this week

**Comment by AilisObrian** [comment]
@valorkin knock knock. sorry for bothering you. but I really want to use this for shrinkwrapping my package.json to deployable isolated package.

**Comment by alexmt** [comment]
@valorkin , could you please publish it?

**Pull request merged**
