### PR TITLE
upgraded to the latest modules from angular2 and ngbootstrap

### PR DESCRIPTION
**Pull request by feedyourmind**
this fixes issue #182
(make it work with angular ^2.0.0-rc.1 #182) https://github.com/valor-software/ng2-select/issues/182

### CODE REVIEW

**Comment by sqwk** [comment]
+1

**Comment by linusbrolin** [comment]
What's the status of this?
I see that the checks have failed, but from what I could see in the details, the failed checks are for not finding the '@angular' components.
If the build system has not been updated to ^2.0.0-rc.1, then obviously the checks will fail.

**Comment by valorkin** [comment]
Sorry for delay, I will update ng2-select today, latest tomorrow

**Comment by ceballos59** [comment]
D:\meanproject\ng2-select-development>npm install

> ng2-select@1.0.1-beta.0 prepublish D:\meanproject\ng2-select-development
> npm run flow.clean && npm run flow.compile
> 
> ng2-select@1.0.1-beta.0 flow.clean D:\meanproject\ng2-select-development
> del bundles coverage demo-build typings "components/*_/_.+(js|d.ts|js.map)" di
> st "ng2-select.+(js|d.ts|js.map)"

No se pudo encontrar D:\meanproject\ng2-select-development\bundles
El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del v

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\node\node.exe" "D:\node\node_modules\npm\bin\npm-cli.js
" "run" "flow.clean"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! ng2-select@1.0.1-beta.0 flow.clean: `del bundles coverage demo-build ty
pings "components/**/*.+(js|d.ts|js.map)" dist "ng2-select.+(js|d.ts|js.map)"`
npm ERR! Exit status 123
npm ERR!
npm ERR! Failed at the ng2-select@1.0.1-beta.0 flow.clean script 'del bundles co
verage demo-build typings "components/**/*.+(js|d.ts|js.map)" dist "ng2-select.+
(js|d.ts|js.map)"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng2-select package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     del bundles coverage demo-build typings "components/**/*.+(js|d.ts|
js.map)" dist "ng2-select.+(js|d.ts|js.map)"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng2-select
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ng2-select
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\meanproject\ng2-select-development\npm-debug.log

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fseve
nts@1.0.12
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\node\node.exe" "D:\node\node_modules\npm\bin\npm-cli.js
" "install"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! ng2-select@1.0.1-beta.0 prepublish: `npm run flow.clean && npm run flow
.compile`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ng2-select@1.0.1-beta.0 prepublish script 'npm run flow.c
lean && npm run flow.compile'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng2-select package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run flow.clean && npm run flow.compile
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng2-select
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ng2-select
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\meanproject\ng2-select-development\npm-debug.log

D:\meanproject\ng2-select-development>clear

**Comment by valorkin** [comment]
You will not be able to run it on windows, use osx or Linux

**Pull request merged**
