### PR TITLE
Update angular to 2.2.x & support for async items

### PR DESCRIPTION
**Pull request by Riron**
@valorkin this is needed in order to upgrade to newer version of Angular

### CODE REVIEW

**Comment by minhoryang** [comment]
related with #475

**Comment by ragafus** [comment]
Support for async items would be a great feature. The options property of the SelectComponent in the current version is not updated when items change, so the search can not be done with async items.

@valorkin

**Comment by valorkin** [comment]
I like your idea

**Comment by Riron** [comment]
Too old, not relevant anymore. Closing PR

**Pull request closed without merging**
