### PR TITLE
feat: programmatically select active items

### PR DESCRIPTION
**Pull request by Namek**
Add `active` property which describes currently selected items.
Remove `initData` property since everything works on top of `active`.

### CODE REVIEW

**Comment by Namek** [comment]
if possibly merged in, a thing that is left is to update `README.md` (remove info about `initData` and add `active`)

**Comment by valorkin** [comment]
@Namek ok, looks really good to me!
2 things:
1. please add Readme update
2. fix tslint issues :)

**Comment by Namek** [comment]
@valorkin done, that should be it.

To make it more angular-way we should enable two-way databinding by merging `active` input with `selected` output into `@Input() selected` + `@Output() selectedChange`.

In case you didn't know what I'm talking about, these two snippets are equal:

```
<input type="text" class="form-control" required
  [ngModel]="model.name"
  (ngModelChange)="model.name = $event" >
```

```
<input type="text" class="form-control" required
  [(ngModel)]="model.name">
```

(source: https://angular.io/docs/ts/latest/guide/forms.html)

But I think if `selected` would be changed to `selectedChange` then we should also rename other outputs. I didn't PR'ed this because I'm not sure if you like it.

**Comment by achimha** [comment]
Any timeline when this will be merged and released to NPM?

**Comment by valorkin** [comment]
Usually Monday - Tuesday is release days

**Comment by EricSch** [comment]
When will this change merged? Seems it is still open
Thanks

**Comment by EricSch** [comment]
Am I wrong? I don't see the changes published to NPM. 
Thanks

**Comment by cbergoon** [comment]
Again, any timeline on when this will be merged in?

**Comment by JohnCashmore** [comment]
Any update one when it will be published to npm?

**Comment by rkralston** [comment]
I'm releasing a product and really need this now.

**Comment by ghost** [comment]
Hey guys, thanks a lot for this awesome directive! I could not make [active] property works. I have tried with everything Array<any>, any[], cast element as SelectItem but nothing, there is no way for me to set the directive with initial data. It seems to be that this issue is related to that. We are using this in PRD so the sooner you could fix this or merge the fix, will be more than appreciated. Thanks in advance.

**Pull request merged**
