### PR TITLE
Adds functionality to make ng2-select compatible with form-controls

### PR DESCRIPTION
**Pull request by sonukapoor**
Please review attached PR. It allows you to use the ng2-select component with ngModel. 

Simple usage:

Add the following attributes:

`name` is the name of your control. 
`[(ngModel)]` should be set to your selected items. It's should be the same as `[active]`. 

`<form #form="ngForm">
      <ng-select required
        name="mySelect"
        #mySelect="ngModel"
        [(ngModel)]="selectedItems"
        [active]="selectedItems"
        [items]="newItems">
      </ng-select>
</form>`

Is Form Valid: {{ form.valid }}<br/>
Is Control Valid: {{ mySelect.valid }}

Note: I have tested this only with template forms. 

Feedback is appreciated.

### CODE REVIEW

**Comment by sonukapoor** [comment]
@valorkin Any chance to get this merged?

**Comment by eamonn** [comment]
@sonukapoor good work. Any chance you can merge this @valorkin ???

**Comment by valorkin** [comment]
thanks for contributing!
please remove package-lock

I am addressing this PR to ngx team, we will try to publish it soon

**Comment by sonukapoor** [comment]
Will do.

**Comment by sonukapoor** [comment]
@valorkin done. I also reverted the other files. Please also note that my vs code formatted the file with proper spaces etc. and when reviewing you should ignore the white spaces:

https://github.com/valor-software/ng2-select/pull/881/files?w=1

**Comment by mohamedfathii** [comment]
when this PR will be merged ?

**Comment by sonukapoor** [comment]
I have a separate fork with the compiled version of the ng2-select using this PR that is available for anybody that wants to use it:

https://github.com/sonukapoor/ng2-select-forms

**Comment by IlyaSurmay** [comment]
I'm updating dependencies right now so we'll be able to test it soon, then it will be merged.

**Review by IlyaSurmay — APPROVED** [review]

**Pull request merged**
